[package]
name = "min-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
anyhow = "1.0.66"
itertools = "0.10.5"
sourcemap = "6.2.0"